#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

sudo: false

matrix:
    include:
        - os: linux
          compiler: clang
          env: USE_PYTHON_VERSION=2
        - os: linux
          compiler: clang
          env: USE_PYTHON_VERSION=3
        - os: linux
          compiler: gcc
          env: USE_PYTHON_VERSION=2
        - os: linux
          compiler: gcc
          env: USE_PYTHON_VERSION=3
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env: USE_PYTHON_VERSION=2 PYTHON_SUFFIX=2 BOOST_PYTHON_OPTION=
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env: USE_PYTHON_VERSION=3 PYTHON_SUFFIX=3 BOOST_PYTHON_OPTION="--with-python3 --without-python"
        - os: osx
          osx_image: xcode7
          compiler: clang
          env: USE_PYTHON_VERSION=2 PYTHON_SUFFIX= BOOST_PYTHON_OPTION=
        - os: osx
          osx_image: xcode7
          compiler: clang
          env: USE_PYTHON_VERSION=3 PYTHON_SUFFIX=3 BOOST_PYTHON_OPTION="--with-python3 --without-python"

# http://docs.travis-ci.com/user/apt/
addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - gcc-4.8
            - libboost-python1.55-dev
            - libboost1.55-dev
            - libsparsehash-dev
            - python-nose
            - python3
            - python3-dev
            - python3-nose
            - python3-setuptools

install:
    - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
    - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
          brew install python$PYTHON_SUFFIX google-sparsehash;
          brew install boost-python $BOOST_PYTHON_OPTION;
          pip$PYTHON_SUFFIX install -q nose;
      fi

script:
    - if [ "${CXX}" = 'g++' ]; then
          CXX=g++-4.8;
          CC=gcc-4.8;
      fi
    - python${USE_PYTHON_VERSION} --version
    - python${USE_PYTHON_VERSION} setup.py build
    - cd test
    - python${USE_PYTHON_VERSION} run_tests.py

