environment:

  matrix:
    - PYTHON: "C:\\Python27-x64"
      DEVPACK: pyosmium_libs27-b63.7z
    - PYTHON: "C:\\Python36-x64"
      DEVPACK: pyosmium_libs36-b63.7z

os: Visual Studio 2015

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - SET VS90COMNTOOLS=%VS140COMNTOOLS%
  - cd "c:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\"
  - ren "Visual C++ for Python" "Visual C++ for Python Do Not Use"
  - cd "C:\Program Files (x86)\"
  - ren "Microsoft Visual Studio 9.0" "Microsoft Visual Studio 9.0 Do Not Use"
  - python --version
  - cd c:\
  - if exist libs ( rmdir c:\libs /s /q )
  - pip install nose wheel

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\dev\pyosmium

build_script:
  - cd c:\dev\pyosmium
  - pip install -i https://testpypi.python.org/pypi osmium
  - cd test
  - python run_tests.py
